#!/bin/sh
# \
exec tclsh "$0" "$@"

# plots of field vectors, cavity profile, and particles
if [catch {exec sddsplot -filter=column,r,-1,30e-3 \
    "-title=spiffe simulation of a DC gun" \
    -groupby=page -split=page -sep=page \
    -col=z,r,Ez,Er dc.fld -arrow=auto,cart,scale=2 \
    -sparse=3 \
    -column=z,r dc.snap -graph=dot,type=2,vary -split=page,column=r0,width=0.5e-3 \
    -column=z,r dc.bnd -omnipresent -graph=line,type=1} result] {
    puts stderr "$result"
}
# plots of Ez vs z
if [catch {exec sddsplot -col=z,Ez -filter=col,r,-1e-5,1e-5 dc.fld -same -split=page -sep=page \
    "-title=On-axis Ez field" } result] {
    puts stderr "$result"
}
# plots of Er vs z
if [catch {exec sddsplot -col=z,Er -filter=col,r,1e-3,1.1e-3 dc.fld -same -split=page -sep=page \
    "-title=Er field at 1mm" } result] {
    puts stderr "$result"
}

# plots of particles at "screens"
if [catch {exec sddsplot dc.sc1 -graph=dot,vary \
    "-title=Phase space at the first screen." \
    -split=column=r0,width=0.5e-3 \
    -col=r,pr -end -col=t,pz -end } result] {
    puts stderr "$result"
}
if [catch {exec sddsplot dc.sc2 -graph=dot,vary \
    "-title=Phase space at the second screen." \
    -split=column=r0,width=0.5e-3 \
    -col=r,pr -end -col=t,pz -end } result] {
    puts stderr "$result"
}
